chore: distinguish between z32 and PublicKey types (#94)
* fix: correct telegram link (#92)

* chore: add issue templates (#91)

* chore: add issue templates (copied from pubky-app)

* chore: missing final newlines

---------

Co-authored-by: Miguel Medeiros <miguel@miguelmedeiros.com.br>

* Repo is now public

Repo is now public, plz update readme again if you think something more is needed

* feat: enhance onboarding store with persistence and rehydration tests (#95)

* fix: missing space and correct date on privacy policy (#137)

* chore: run format:check with useful message in pre-commit hook to prevent committing unformatted code (#114)

* feat: consume bootstrap endoint when signIn

* feat: delete bootstrap controller and replace with bootstrap service

* chore: fix lint warnings

* chore: distinguish between z32 and PublicKey types

* refactor: improve recovery file download handling by utilizing ArrayBuffer

---------

Co-authored-by: James <74595920+catch-21@users.noreply.github.com>
Co-authored-by: Miguel Medeiros <miguel@miguelmedeiros.com.br>
Co-authored-by: John Carvalho <18273620+BitcoinErrorLog@users.noreply.github.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,7 +3,10 @@
 echo "🔍 Running pre-commit checks..."
 
 echo "✨ Formatting code..."
-npm run format
+if ! npm run format:check; then
+  echo "❌ Code formatting check failed. Run \`npm run format\` to fix formatting issues then add changes and commit again."
+  exit 1
+fi
 
 echo "🧪 Running tests..."
 npm run test
